# 应用名称
spring:
  application:
    name: amen
  #   mvc:
  #     pathmatch:
  #       matching-strategy: ANT_PATH_MATCHER
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/yeone?serverTimezone=GMT%2b8

    # 数据库用户名&密码：
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
# 应用服务 WEB 访问端口
server:
  port: 9090
#下面这些内容是为了让MyBatis映射
#指定Mybatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/springboot后台/小白毕设/files/







