# 应用名称
spring:
  application:
    name: amen
  #   mvc:
  #     pathmatch:
  #       matching-strategy: ANT_PATH_MATCHER
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/yeone?serverTimezone=GMT%2b8

    # 数据库用户名&密码：
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# 应用服务 WEB 访问端口
server:
  port: 9090
#下面这些内容是为了让MyBatis映射
#指定Mybatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/springboot后台/小白毕设/files/
alipay:
  appId: 2021000121653841
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClYlbvoDeoERgLe5/JQDW/leR1FXq8I9AVqReD0txqbNg0DS0q8Zz0Y1YkBhTvEkiZTjGw9Gah8cEynuJ7UIlqPjljQYEhpyLhJk2hyboXLXM5g4jcnhGBi9s25R2iOFP320mTMSzcOsQUcOBKfOr3SnD3M961r2h+xKTcJTxuFNtbxfIx64bveCcsTnLsE2z+21kIq2z/GPE5z+f+48rJpdARsjHpOUS+7shtxUhr7h2UNhI2ezv9bvgk4DRS2bUD7lInOEEWnvoTJsTEVmRZAu4hM0XS1DUwPhCJB5Qf5rW7WuJRpNktvZvFtcMLg21vjtx6foCC5EjXmk/Jb4elAgMBAAECggEBAIK9wB5FGVqa0NhbDZFKWnMvauCIb3OGGDzXZMiIjEjx7OUROZDGWp70XKezyx7H5G6VW0EZpH0HogSDiGWV4FwF/tYRdaUF/NPitOJel+c0ve9MpYhKyWoRBuZZr9iLEQ5S49IhwOYE6veB2D3qjNGbnrw93CTjGweEKxQBt8kJGmjg26GqHvFntF7yRXC+o1H9c9RiHdYBNXU1+j8uEyxCTQxC4OMf3TcBV2UJKTw6A7GZxjNSHEaoDU8k8LTW0zmCNmUXrkLXczN69bXtU/+txuD7hT6xJmLFpsapJXBSrw9131chd8tAanMvpVBhZP6/eQ6FFDRumCwyAP3hdsECgYEA5zmVNd3Njy7rmlPCOJRvijeLj5cEGL2rvGADw9HCKSntkpQgKJGvihHg+GEFMMkZpq8Mb5ZPwsFfGCtYaLwbc8GLgBl8QZ0q+HknZlnqAhugUcC6mF8oTjXHw9aZI7ntxqlwhkzTkeORpl/HPu5v7ZdPD1nApPb4hjQxNkAg73ECgYEAtxrEb7AFKOos99wY6uMpBuGJL2CYxrBXkkwTciXn3JnJsi9G7x5scN1WPT052knvoHKlvDIvvCKRkAAAkchTZUi+Q2nsJgDnSjBCalWirGICu8UHQCVbJby9tmIjCRMxAUhacTi7IJisBFKYoVDrw9/0iZif/8cum2+IH/IZKXUCgYBBUuhPnokbYYMYR3+AYpccclLQTzbOEo+5GVsW8GStInZGyehH7dis5h4rraU8wiOoDp4xzEJeYCkQd/ZzKGmNC2nw18Jd+xwPtJKn/ND6pXlmf094CrIlXlZAgpkjGb0OOgJbPssq1SLp4Pc2VUBz3CJu0Ml3EXrm10nr7LQhUQKBgCN3RdE0UOuJ4EfqE9F7SnkQule46B6kDXJC1gloGi76grzGt4Cdbfe2h3u5HjmP1KBJVJzNQ723HGa9+V5DZRPbMS8xlxINXr9Z9aNPDwFAwrLICQ19rtfyZPSssYiSdQ2AjDQd/vDjYX482V91oxT/jggQzfznAboNslottH35AoGAARVD3ILe7MZfoTGnKpSnoI4Ng/5eGW3KImzrA8scjhoHTEn3L6tENMmHmlX1nqGLjo23fLw0KSZwrV9gA2nRktHNdCMowMMjslJyYy1gfaMK34GCFDB8Ub/SYz/7vtxLVuAiLJYVRSTyZPrkLRDo0yoNifWg3RltLmy1PG0mKIc=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4bYqClQyercVLkUXALggb2rbp1pRIne8EyL6jgP/wm+LhtmsJqV5X+WGLXsz/NCU93vurR1KiVtbUdzP5HFGM9PAkYMRUuo7ndd2yMJtUqRE5QGj0JjunLvMlHc0HNAbRsvaLGLoGmbL8pn1rlHBXRROoPS4PmcM5dVTZR1lLNuoqPC9ssZgCB/AVyhGSXmUcJu+yCRhB2Ga4D5qDSw/vxOMBhb8djFeYhYUHsfDm/jvc/L+w/00PbZlRkeiY/YXCx9vaaWGaE5jKsliREPJLQpxtz8B3kusZL8B7UuXDmGdqImhpAscUdn7Iz1yDeMYJ3t4OniAiYx0zf6MhYYvawIDAQAB
  notifyUrl: http://cagds3.natappfree.cc/alipay/notify






